const data = {
    "status": "OK",
    "result": {
        "data": {
            "content": {
                "problemCode": "SUMSLOPE",
                "problemName": "Summing Slopes",
                "dateAdded": "2010-04-11",
                "languagesSupported": [
                    "C++ 6.3",
                    "PAS gpc",
                    "PERL",
                    "PYTH",
                    "FORT",
                    "WSPC",
                    "ADA",
                    "CAML",
                    "ICK",
                    "JAVA",
                    "C",
                    "BF",
                    "ASM",
                    "CLPS",
                    "PRLG",
                    "ICON",
                    "RUBY",
                    "SCM qobi",
                    "PIKE",
                    "D",
                    "HASK",
                    "PAS fpc",
                    "ST",
                    "NICE",
                    "LUA",
                    "C#",
                    "BASH",
                    "PHP",
                    "NEM",
                    "LISP sbcl",
                    "LISP clisp",
                    "SCM guile",
                    "C99 strict",
                    "JS",
                    "ERL",
                    "SCALA",
                    "SQL",
                    "C++ 4.3.2",
                    null,
                    null,
                    "C++14",
                    null,
                    null,
                    "KTLN",
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    "PERL6",
                    null,
                    "NODEJS",
                    null,
                    null,
                    "DOC",
                    "PDF",
                    "PS",
                    "TEXT",
                    "C++17",
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    "swift",
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    "rust",
                    null,
                    null,
                    null,
                    "SCM chicken",
                    null,
                    "PYPY",
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    "PYPY3",
                    null,
                    "CLOJ",
                    null,
                    null,
                    "GO",
                    null,
                    "PYTH 3.6",
                    "R",
                    "COB",
                    null,
                    null,
                    null,
                    null,
                    null,
                    "F#",
                    null,
                    null,
                    null
                ],
                "sourceSizeLimit": 10000,
                "maxTimeLimit": 0,
                "challengeType": "binary",
                "author": "syco_adm",
                "successfulSubmissions": 19,
                "totalSubmissions": 122,
                "partialSubmissions": 0,
                "tags": [
                    "may10",
                    "medium"
                ],
                "body": "<p><br />A digit in a number N is a minima if it is lesser than both the digits adjacent to it. Similarly, a digit is a maxima if it is greater than both the digits adjacent to it. The slope of N is the number of digits in N (leaving out the first and the last digit) which are either a minima or a maxima. Given A and B, count the sum of the slopes of all numbers between A and B.<br /></p><br /><br /><p><br />Input :<br /></p><br /><p><br />The first line contains the number of test cases T. Each of the next T lines contains two integers A and B.<br /></p><br /><br /><p><br />Output :<br /></p><br /><p><br />Output T lines one for each test case, containing the required sum for the corresponding test case.<br /></p><br /><br /><pre><br />Sample Input :<br />3<br />101 101<br />1 100<br />100 150<br /><br /></pre><br /><br /><pre><br />Sample Output :<br />1<br />0<br />19<br /><br /></pre><br /><pre><br />Constraints :<br />1 <= T <= 50000<br />1 <= A <= B <= 1000000000000000 (10^15)<br /></pre>"
            },
            "code": 9001,
            "message": "Contest Problem Successfully fetched"
        }
    }
};

module.exports = data;